-- WithTrip travel plan schema
-- Target: Oracle Database 19c+
-- Source: travelplanner_v2.exerd and KMS-travel-plan-handoff.md
-- Run once as the application schema owner.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET DEFINE OFF

CREATE SEQUENCE SEQ_TRAVEL_PLAN
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_PLAN_DAY
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_PLAN_SCHEDULE_ITEM
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_PLAN_INVITATION
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE TABLE REGION_MASTER (
    REGION_CODE        VARCHAR2(20)  NOT NULL,
    REGION_NAME        VARCHAR2(100) NOT NULL,
    PARENT_REGION_CODE VARCHAR2(20),
    REGION_LEVEL       VARCHAR2(10)  NOT NULL,
    DISPLAY_ORDER      NUMBER(5)     DEFAULT 0 NOT NULL,
    ACTIVE_YN          CHAR(1)       DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_REGION_MASTER PRIMARY KEY (REGION_CODE),
    CONSTRAINT FK_REGION_PARENT
        FOREIGN KEY (PARENT_REGION_CODE) REFERENCES REGION_MASTER (REGION_CODE),
    CONSTRAINT CK_REGION_LEVEL
        CHECK (REGION_LEVEL IN ('SIDO', 'SIGUNGU')),
    CONSTRAINT CK_REGION_ACTIVE
        CHECK (ACTIVE_YN IN ('Y', 'N')),
    CONSTRAINT CK_REGION_PARENT
        CHECK (
            (REGION_LEVEL = 'SIDO' AND PARENT_REGION_CODE IS NULL)
            OR (REGION_LEVEL = 'SIGUNGU' AND PARENT_REGION_CODE IS NOT NULL)
        )
);

CREATE TABLE PLACE_MASTER (
    PLACE_PROVIDER    VARCHAR2(30)                 NOT NULL,
    EXTERNAL_PLACE_ID VARCHAR2(100)                NOT NULL,
    PLACE_TYPE        VARCHAR2(30)                 NOT NULL,
    PLACE_NAME        VARCHAR2(200)                NOT NULL,
    CATEGORY_NAME     VARCHAR2(100),
    ADDRESS           VARCHAR2(500),
    DESCRIPTION       CLOB,
    LATITUDE          NUMBER(10, 7),
    LONGITUDE         NUMBER(10, 7),
    IMAGE_URL         VARCHAR2(1000),
    ACTIVE_YN         CHAR(1)                      DEFAULT 'Y' NOT NULL,
    SYNCED_AT         TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_AT        TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PLACE_MASTER
        PRIMARY KEY (PLACE_PROVIDER, EXTERNAL_PLACE_ID),
    CONSTRAINT CK_PLACE_ACTIVE
        CHECK (ACTIVE_YN IN ('Y', 'N')),
    CONSTRAINT CK_PLACE_LATITUDE
        CHECK (LATITUDE BETWEEN -90 AND 90),
    CONSTRAINT CK_PLACE_LONGITUDE
        CHECK (LONGITUDE BETWEEN -180 AND 180)
);

CREATE TABLE TRAVEL_PLAN (
    PLAN_ID               NUMBER(19)                   NOT NULL,
    SOURCE_PLAN_ID        NUMBER(19),
    OWNER_MEMBER_ID       NUMBER(19)                   NOT NULL,
    TITLE                 VARCHAR2(200)                NOT NULL,
    REGION_CODE           VARCHAR2(20)                 NOT NULL,
    START_DATE            DATE                         NOT NULL,
    END_DATE              DATE                         NOT NULL,
    VISIBILITY            VARCHAR2(10)                 DEFAULT 'PUBLIC' NOT NULL,
    PLAN_STATUS           VARCHAR2(10)                 DEFAULT 'ACTIVE' NOT NULL,
    VERSION_NO            NUMBER(10)                   DEFAULT 0 NOT NULL,
    DELETED_AT            TIMESTAMP(6) WITH TIME ZONE,
    DELETED_BY_MEMBER_ID  NUMBER(19),
    RESTORED_AT           TIMESTAMP(6) WITH TIME ZONE,
    RESTORED_BY_ADMIN_ID  NUMBER(19),
    CREATED_AT            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VIEW_COUNT            NUMBER(6)                    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TRAVEL_PLAN PRIMARY KEY (PLAN_ID),
    CONSTRAINT FK_PLAN_REGION
        FOREIGN KEY (REGION_CODE) REFERENCES REGION_MASTER (REGION_CODE),
    CONSTRAINT CK_PLAN_VISIBILITY
        CHECK (VISIBILITY IN ('PUBLIC', 'PRIVATE')),
    CONSTRAINT CK_PLAN_STATUS
        CHECK (PLAN_STATUS IN ('ACTIVE', 'DELETED')),
    CONSTRAINT CK_PLAN_DATE_RANGE
        CHECK (START_DATE <= END_DATE),
    CONSTRAINT CK_PLAN_DURATION
        CHECK ((END_DATE - START_DATE) BETWEEN 0 AND 13),
    CONSTRAINT CK_PLAN_DELETE_STATE
        CHECK (
            (PLAN_STATUS = 'ACTIVE' AND DELETED_AT IS NULL AND DELETED_BY_MEMBER_ID IS NULL)
            OR (PLAN_STATUS = 'DELETED' AND DELETED_AT IS NOT NULL AND DELETED_BY_MEMBER_ID IS NOT NULL)
        ),
    CONSTRAINT CK_PLAN_VERSION
        CHECK (VERSION_NO >= 0),
    CONSTRAINT CK_PLAN_VIEW_COUNT
        CHECK (VIEW_COUNT >= 0)
);

CREATE TABLE PLAN_MEMBER (
    PLAN_ID          NUMBER(19)                   NOT NULL,
    MEMBER_ID        NUMBER(19)                   NOT NULL,
    PARTICIPANT_TYPE VARCHAR2(10)                 NOT NULL,
    JOINED_AT        TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PLAN_MEMBER PRIMARY KEY (PLAN_ID, MEMBER_ID),
    CONSTRAINT FK_PLAN_MEMBER_PLAN
        FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID),
    CONSTRAINT CK_PLAN_PARTICIPANT_TYPE
        CHECK (PARTICIPANT_TYPE IN ('CREATOR', 'INVITEE'))
);

CREATE TABLE PLAN_DAY (
    PLAN_DAY_ID      NUMBER(19) NOT NULL,
    PLAN_ID          NUMBER(19) NOT NULL,
    DAY_NO           NUMBER(2)  NOT NULL,
    TRAVEL_DATE      DATE       NOT NULL,
    SCHEDULE_VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PLAN_DAY PRIMARY KEY (PLAN_DAY_ID),
    CONSTRAINT UK_PLAN_DAY_NO UNIQUE (PLAN_ID, DAY_NO),
    CONSTRAINT UK_PLAN_DAY_DATE UNIQUE (PLAN_ID, TRAVEL_DATE),
    CONSTRAINT FK_PLAN_DAY_PLAN
        FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID),
    CONSTRAINT CK_PLAN_DAY_NO
        CHECK (DAY_NO BETWEEN 1 AND 14),
    CONSTRAINT CK_PLAN_DAY_VERSION
        CHECK (SCHEDULE_VERSION >= 0)
);

CREATE TABLE PLAN_SCHEDULE_ITEM (
    SCHEDULE_ITEM_ID      NUMBER(19)                   NOT NULL,
    PLAN_DAY_ID           NUMBER(19)                   NOT NULL,
    TIME_SLOT             VARCHAR2(10)                 DEFAULT 'MORNING' NOT NULL,
    POSITION_NO           NUMBER(4)                    NOT NULL,
    PLACE_PROVIDER        VARCHAR2(30)                 NOT NULL,
    EXTERNAL_PLACE_ID     VARCHAR2(100)                NOT NULL,
    PLACE_NAME_SNAPSHOT   VARCHAR2(200)                NOT NULL,
    CATEGORY_SNAPSHOT     VARCHAR2(100),
    ADDRESS_SNAPSHOT      VARCHAR2(500),
    LATITUDE_SNAPSHOT     NUMBER(10, 7),
    LONGITUDE_SNAPSHOT    NUMBER(10, 7),
    IMAGE_URL_SNAPSHOT    VARCHAR2(1000),
    DESCRIPTION_SNAPSHOT  CLOB,
    ITEM_VERSION          NUMBER(10)                   DEFAULT 0 NOT NULL,
    CREATED_AT            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PLAN_SCHEDULE_ITEM PRIMARY KEY (SCHEDULE_ITEM_ID),
    CONSTRAINT UK_PLAN_ITEM_POSITION
        UNIQUE (PLAN_DAY_ID, TIME_SLOT, POSITION_NO),
    CONSTRAINT UK_PLAN_ITEM_PLACE_SLOT
        UNIQUE (PLAN_DAY_ID, TIME_SLOT, PLACE_PROVIDER, EXTERNAL_PLACE_ID),
    CONSTRAINT FK_PLAN_ITEM_DAY
        FOREIGN KEY (PLAN_DAY_ID) REFERENCES PLAN_DAY (PLAN_DAY_ID),
    CONSTRAINT CK_PLAN_ITEM_TIME
        CHECK (TIME_SLOT IN ('MORNING', 'AFTERNOON')),
    CONSTRAINT CK_PLAN_ITEM_POSITION
        CHECK (POSITION_NO >= 1),
    CONSTRAINT CK_PLAN_ITEM_LAT
        CHECK (LATITUDE_SNAPSHOT BETWEEN -90 AND 90),
    CONSTRAINT CK_PLAN_ITEM_LNG
        CHECK (LONGITUDE_SNAPSHOT BETWEEN -180 AND 180),
    CONSTRAINT CK_PLAN_ITEM_VERSION
        CHECK (ITEM_VERSION >= 0)
);

CREATE TABLE PLAN_EDIT_OPERATION (
    OPERATION_ID   VARCHAR2(36)                 NOT NULL,
    PLAN_ID        NUMBER(19)                   NOT NULL,
    MEMBER_ID      NUMBER(19)                   NOT NULL,
    OPERATION_TYPE VARCHAR2(10)                 NOT NULL,
    TARGET_ITEM_ID NUMBER(19),
    BASE_VERSION   NUMBER(10),
    RESULT_VERSION NUMBER(10),
    CREATED_AT     TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PLAN_EDIT_OPERATION PRIMARY KEY (OPERATION_ID),
    CONSTRAINT FK_PLAN_OPERATION_PLAN
        FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID),
    CONSTRAINT CK_PLAN_OPERATION_TYPE
        CHECK (OPERATION_TYPE IN ('ADD', 'UPDATE', 'DELETE', 'MOVE', 'REORDER')),
    CONSTRAINT CK_PLAN_OPERATION_VERSION
        CHECK (
            (BASE_VERSION IS NULL OR BASE_VERSION >= 0)
            AND (RESULT_VERSION IS NULL OR RESULT_VERSION >= 0)
        )
);

CREATE TABLE PLAN_INVITATION (
    INVITATION_ID      NUMBER(19)                   NOT NULL,
    PLAN_ID            NUMBER(19)                   NOT NULL,
    INVITER_MEMBER_ID  NUMBER(19)                   NOT NULL,
    INVITEE_MEMBER_ID  NUMBER(19),
    INVITEE_EMAIL      VARCHAR2(254)                NOT NULL,
    INVITATION_STATUS  VARCHAR2(10)                 DEFAULT 'PENDING' NOT NULL,
    INVITATION_TOKEN   VARCHAR2(128)                NOT NULL,
    EXPIRES_AT         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    RESPONDED_AT       TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT         TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PLAN_INVITATION PRIMARY KEY (INVITATION_ID),
    CONSTRAINT UK_PLAN_INVITATION_TOKEN UNIQUE (INVITATION_TOKEN),
    CONSTRAINT FK_INVITATION_PLAN
        FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID),
    CONSTRAINT CK_INVITATION_STATUS
        CHECK (INVITATION_STATUS IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELED')),
    CONSTRAINT CK_INVITATION_EXPIRY
        CHECK (EXPIRES_AT > CREATED_AT)
);

CREATE INDEX IX_REGION_NAME_ACTIVE
    ON REGION_MASTER (REGION_NAME, ACTIVE_YN);

CREATE INDEX IX_REGION_PARENT_NAME
    ON REGION_MASTER (PARENT_REGION_CODE, REGION_NAME);

CREATE INDEX IX_PLACE_NAME_ACTIVE
    ON PLACE_MASTER (PLACE_NAME, ACTIVE_YN);

CREATE INDEX IX_PLAN_OWNER_UPDATED
    ON TRAVEL_PLAN (OWNER_MEMBER_ID, SYS_EXTRACT_UTC(UPDATED_AT) DESC);

CREATE INDEX IX_PLAN_PUBLIC_UPDATED
    ON TRAVEL_PLAN (VISIBILITY, PLAN_STATUS, SYS_EXTRACT_UTC(UPDATED_AT) DESC);

CREATE INDEX IX_PLAN_REGION_PUBLIC
    ON TRAVEL_PLAN (REGION_CODE, VISIBILITY, PLAN_STATUS);

CREATE INDEX IX_PLAN_MEMBER_MEMBER
    ON PLAN_MEMBER (MEMBER_ID, PLAN_ID);

CREATE INDEX IX_PLAN_OPERATION_CREATED
    ON PLAN_EDIT_OPERATION (PLAN_ID, SYS_EXTRACT_UTC(CREATED_AT) DESC);

CREATE INDEX IX_INVITE_EMAIL_STATUS
    ON PLAN_INVITATION (INVITEE_EMAIL, INVITATION_STATUS);

CREATE INDEX IX_INVITE_MEMBER_STATUS
    ON PLAN_INVITATION (INVITEE_MEMBER_ID, INVITATION_STATUS);

CREATE INDEX IX_INVITE_PLAN_STATUS
    ON PLAN_INVITATION (PLAN_ID, INVITATION_STATUS);

COMMENT ON TABLE REGION_MASTER IS 'TourAPI 국내 시도 및 시군구 기준정보';
COMMENT ON COLUMN REGION_MASTER.REGION_CODE IS 'SIDO는 TourAPI areaCode, SIGUNGU는 areaCode-sigunguCode';
COMMENT ON TABLE PLACE_MASTER IS '외부 관광 장소 최신 기본정보';
COMMENT ON COLUMN PLACE_MASTER.PLACE_PROVIDER IS '장소 제공자 식별값. TourAPI는 TOUR_API 사용';
COMMENT ON TABLE TRAVEL_PLAN IS '여행 플랜 기본정보와 전체 낙관적 잠금 버전';
COMMENT ON COLUMN TRAVEL_PLAN.OWNER_MEMBER_ID IS '인증 연동 후 MEMBER.MEMBER_ID 외래키 적용';
COMMENT ON TABLE PLAN_MEMBER IS '플랜 생성자와 초대 참여자';
COMMENT ON TABLE PLAN_DAY IS '여행 날짜별 일정과 일정 낙관적 잠금 버전';
COMMENT ON TABLE PLAN_SCHEDULE_ITEM IS '장소 정보를 추가 시점의 Snapshot으로 보관하는 일정 항목';
COMMENT ON TABLE PLAN_EDIT_OPERATION IS '중복 요청 방지와 변경 추적을 위한 편집 작업 이력';
COMMENT ON COLUMN PLAN_EDIT_OPERATION.OPERATION_ID IS '클라이언트 또는 서버가 생성한 UUID 문자열';
COMMENT ON TABLE PLAN_INVITATION IS '플랜 참여 초대와 Token 상태';

COMMIT;
