-- Optional identity foreign keys.
-- Run only after the MEMBER and ADMIN tables are finalized and created.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
    MEMBER_COLUMN_COUNT NUMBER;
    ADMIN_COLUMN_COUNT  NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO MEMBER_COLUMN_COUNT
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'MEMBER'
       AND COLUMN_NAME = 'MEMBER_ID'
       AND DATA_TYPE = 'NUMBER';

    SELECT COUNT(*)
      INTO ADMIN_COLUMN_COUNT
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ADMIN'
       AND COLUMN_NAME = 'ADMIN_ID'
       AND DATA_TYPE = 'NUMBER';

    IF MEMBER_COLUMN_COUNT <> 1 OR ADMIN_COLUMN_COUNT <> 1 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'MEMBER.MEMBER_ID and ADMIN.ADMIN_ID must exist before identity foreign keys are added.'
        );
    END IF;
END;
/

ALTER TABLE TRAVEL_PLAN ADD CONSTRAINT FK_PLAN_OWNER
    FOREIGN KEY (OWNER_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE TRAVEL_PLAN ADD CONSTRAINT FK_PLAN_DELETED_MEMBER
    FOREIGN KEY (DELETED_BY_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE TRAVEL_PLAN ADD CONSTRAINT FK_PLAN_RESTORED_ADMIN
    FOREIGN KEY (RESTORED_BY_ADMIN_ID) REFERENCES ADMIN (ADMIN_ID);

ALTER TABLE PLAN_MEMBER ADD CONSTRAINT FK_PLAN_MEMBER_MEMBER
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE PLAN_EDIT_OPERATION ADD CONSTRAINT FK_PLAN_OPERATION_MEMBER
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE PLAN_INVITATION ADD CONSTRAINT FK_INVITATION_INVITER
    FOREIGN KEY (INVITER_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE PLAN_INVITATION ADD CONSTRAINT FK_INVITATION_INVITEE
    FOREIGN KEY (INVITEE_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

COMMIT;
