-- Read-only verification. Expected result: every query returns zero rows,
-- except the final SIDO count which must return 17.

SET PAGESIZE 100
SET LINESIZE 200

PROMPT [Missing tables]
WITH EXPECTED_TABLES (TABLE_NAME) AS (
    SELECT 'REGION_MASTER' FROM DUAL UNION ALL
    SELECT 'PLACE_MASTER' FROM DUAL UNION ALL
    SELECT 'TRAVEL_PLAN' FROM DUAL UNION ALL
    SELECT 'PLAN_MEMBER' FROM DUAL UNION ALL
    SELECT 'PLAN_DAY' FROM DUAL UNION ALL
    SELECT 'PLAN_SCHEDULE_ITEM' FROM DUAL UNION ALL
    SELECT 'PLAN_EDIT_OPERATION' FROM DUAL UNION ALL
    SELECT 'PLAN_INVITATION' FROM DUAL
)
SELECT EXPECTED.TABLE_NAME
  FROM EXPECTED_TABLES EXPECTED
 WHERE NOT EXISTS (
       SELECT 1
         FROM USER_TABLES ACTUAL
        WHERE ACTUAL.TABLE_NAME = EXPECTED.TABLE_NAME
 );

PROMPT [Missing sequences]
WITH EXPECTED_SEQUENCES (SEQUENCE_NAME) AS (
    SELECT 'SEQ_TRAVEL_PLAN' FROM DUAL UNION ALL
    SELECT 'SEQ_PLAN_DAY' FROM DUAL UNION ALL
    SELECT 'SEQ_PLAN_SCHEDULE_ITEM' FROM DUAL UNION ALL
    SELECT 'SEQ_PLAN_INVITATION' FROM DUAL
)
SELECT EXPECTED.SEQUENCE_NAME
  FROM EXPECTED_SEQUENCES EXPECTED
 WHERE NOT EXISTS (
       SELECT 1
         FROM USER_SEQUENCES ACTUAL
        WHERE ACTUAL.SEQUENCE_NAME = EXPECTED.SEQUENCE_NAME
 );

PROMPT [Missing auto-save columns]
WITH EXPECTED_COLUMNS (TABLE_NAME, COLUMN_NAME) AS (
    SELECT 'PLAN_EDIT_OPERATION', 'REQUEST_HASH' FROM DUAL
)
SELECT EXPECTED.TABLE_NAME, EXPECTED.COLUMN_NAME
  FROM EXPECTED_COLUMNS EXPECTED
 WHERE NOT EXISTS (
       SELECT 1
         FROM USER_TAB_COLUMNS ACTUAL
        WHERE ACTUAL.TABLE_NAME = EXPECTED.TABLE_NAME
          AND ACTUAL.COLUMN_NAME = EXPECTED.COLUMN_NAME
 );

PROMPT [Disabled constraints]
SELECT TABLE_NAME, CONSTRAINT_NAME, STATUS
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME IN (
       'REGION_MASTER',
       'PLACE_MASTER',
       'TRAVEL_PLAN',
       'PLAN_MEMBER',
       'PLAN_DAY',
       'PLAN_SCHEDULE_ITEM',
       'PLAN_EDIT_OPERATION',
       'PLAN_INVITATION'
 )
   AND STATUS <> 'ENABLED';

PROMPT [Invalid indexes]
SELECT TABLE_NAME, INDEX_NAME, STATUS
  FROM USER_INDEXES
 WHERE TABLE_NAME IN (
       'REGION_MASTER',
       'PLACE_MASTER',
       'TRAVEL_PLAN',
       'PLAN_MEMBER',
       'PLAN_DAY',
       'PLAN_SCHEDULE_ITEM',
       'PLAN_EDIT_OPERATION',
       'PLAN_INVITATION'
 )
   AND STATUS <> 'VALID';

PROMPT [SIDO seed count: expected 17]
SELECT COUNT(*) AS SIDO_COUNT
  FROM REGION_MASTER
 WHERE REGION_LEVEL = 'SIDO'
   AND ACTIVE_YN = 'Y';
