-- Read-only verification. Expected result: every diagnostic query returns zero rows,
-- TOUR_SYNC_STATE count returns 1 and the final SIDO count returns 17.

SET PAGESIZE 100
SET LINESIZE 200

PROMPT [Missing tables]
WITH EXPECTED_TABLES (TABLE_NAME) AS (
    SELECT 'REGION_MASTER' FROM DUAL UNION ALL
    SELECT 'PLACE_MASTER' FROM DUAL UNION ALL
    SELECT 'TRAVEL_PLAN' FROM DUAL UNION ALL
    SELECT 'PLAN_MEMBER' FROM DUAL UNION ALL
    SELECT 'PLAN_DAY' FROM DUAL UNION ALL
    SELECT 'PLAN_SCHEDULE_ITEM' FROM DUAL UNION ALL
    SELECT 'PLAN_EDIT_OPERATION' FROM DUAL UNION ALL
    SELECT 'PLAN_INVITATION' FROM DUAL UNION ALL
    SELECT 'TOUR_SYNC_STATE' FROM DUAL UNION ALL
    SELECT 'TOUR_SYNC_HISTORY' FROM DUAL
)
SELECT EXPECTED.TABLE_NAME
  FROM EXPECTED_TABLES EXPECTED
 WHERE NOT EXISTS (
       SELECT 1
         FROM USER_TABLES ACTUAL
        WHERE ACTUAL.TABLE_NAME = EXPECTED.TABLE_NAME
 );

PROMPT [Missing sequences]
WITH EXPECTED_SEQUENCES (SEQUENCE_NAME) AS (
    SELECT 'SEQ_TRAVEL_PLAN' FROM DUAL UNION ALL
    SELECT 'SEQ_PLAN_DAY' FROM DUAL UNION ALL
    SELECT 'SEQ_PLAN_SCHEDULE_ITEM' FROM DUAL UNION ALL
    SELECT 'SEQ_PLAN_INVITATION' FROM DUAL
)
SELECT EXPECTED.SEQUENCE_NAME
  FROM EXPECTED_SEQUENCES EXPECTED
 WHERE NOT EXISTS (
       SELECT 1
         FROM USER_SEQUENCES ACTUAL
        WHERE ACTUAL.SEQUENCE_NAME = EXPECTED.SEQUENCE_NAME
 );

PROMPT [Missing application columns]
WITH EXPECTED_COLUMNS (TABLE_NAME, COLUMN_NAME) AS (
    SELECT 'PLAN_EDIT_OPERATION', 'REQUEST_HASH' FROM DUAL UNION ALL
	SELECT 'TRAVEL_PLAN', 'PUBLISH_STATUS' FROM DUAL UNION ALL
	SELECT 'TRAVEL_PLAN', 'THUMBNAIL_IMG' FROM DUAL UNION ALL
    SELECT 'TOUR_SYNC_STATE', 'LOCK_ID' FROM DUAL UNION ALL
    SELECT 'TOUR_SYNC_STATE', 'LEASE_EXPIRES_AT' FROM DUAL UNION ALL
    SELECT 'TOUR_SYNC_HISTORY', 'SYNC_ID' FROM DUAL UNION ALL
    SELECT 'TOUR_SYNC_HISTORY', 'CHANGED_COUNT' FROM DUAL UNION ALL
    SELECT 'TOUR_SYNC_HISTORY', 'FAILED_COUNT' FROM DUAL UNION ALL
    SELECT 'TOUR_SYNC_HISTORY', 'SYNC_STATUS' FROM DUAL UNION ALL
    SELECT 'TOUR_SYNC_HISTORY', 'MANAGER' FROM DUAL
)
SELECT EXPECTED.TABLE_NAME, EXPECTED.COLUMN_NAME
  FROM EXPECTED_COLUMNS EXPECTED
 WHERE NOT EXISTS (
       SELECT 1
         FROM USER_TAB_COLUMNS ACTUAL
        WHERE ACTUAL.TABLE_NAME = EXPECTED.TABLE_NAME
          AND ACTUAL.COLUMN_NAME = EXPECTED.COLUMN_NAME
 );

PROMPT [Disabled constraints]
SELECT TABLE_NAME, CONSTRAINT_NAME, STATUS
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME IN (
       'REGION_MASTER',
       'PLACE_MASTER',
       'TRAVEL_PLAN',
       'PLAN_MEMBER',
       'PLAN_DAY',
       'PLAN_SCHEDULE_ITEM',
       'PLAN_EDIT_OPERATION',
       'PLAN_INVITATION',
       'TOUR_SYNC_STATE',
       'TOUR_SYNC_HISTORY'
 )
   AND STATUS <> 'ENABLED';

PROMPT [Invalid indexes]
SELECT TABLE_NAME, INDEX_NAME, STATUS
  FROM USER_INDEXES
 WHERE TABLE_NAME IN (
       'REGION_MASTER',
       'PLACE_MASTER',
       'TRAVEL_PLAN',
       'PLAN_MEMBER',
       'PLAN_DAY',
       'PLAN_SCHEDULE_ITEM',
       'PLAN_EDIT_OPERATION',
       'PLAN_INVITATION',
       'TOUR_SYNC_STATE',
       'TOUR_SYNC_HISTORY'
 )
   AND STATUS <> 'VALID';

PROMPT [Legacy TOUR sync objects: expected zero rows]
SELECT TABLE_NAME, COLUMN_NAME
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'TOUR_SYNC_HISTORY'
   AND COLUMN_NAME IN (
       'SYNC_HISTORY_ID',
       'ADMIN_ID',
       'SUCCESS_COUNT',
       'FAIL_COUNT',
       'PROCESS_STATUS'
   )
UNION ALL
SELECT 'SEQUENCE', SEQUENCE_NAME
  FROM USER_SEQUENCES
 WHERE SEQUENCE_NAME = 'SEQ_TOUR_SYNC_HISTORY';

PROMPT [Interrupted TOUR sync migration objects: expected zero rows]
SELECT TABLE_NAME
  FROM USER_TABLES
 WHERE TABLE_NAME = 'TOUR_SYNC_HISTORY_V2';

PROMPT [Preserved TOUR sync backup: informational, may be removed after data verification]
SELECT TABLE_NAME
  FROM USER_TABLES
 WHERE TABLE_NAME = 'TOUR_SYNC_HISTORY_LEGACY';

PROMPT [TOUR sync state row count: expected 1]
SELECT COUNT(*) AS TOUR_SYNC_STATE_COUNT
  FROM TOUR_SYNC_STATE
 WHERE LOCK_ID = 1
   AND RUNNING_YN IN ('Y', 'N');

PROMPT [SIDO seed count: expected 17]
SELECT COUNT(*) AS SIDO_COUNT
  FROM REGION_MASTER
 WHERE REGION_LEVEL = 'SIDO'
   AND ACTIVE_YN = 'Y';
