-- Existing Oracle schemas created before schedule auto-save support need this column.
-- Existing rows receive a deterministic legacy hash before the NOT NULL constraint is enabled.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET DEFINE OFF

ALTER TABLE PLAN_EDIT_OPERATION
    ADD REQUEST_HASH VARCHAR2(64);

UPDATE PLAN_EDIT_OPERATION
   SET REQUEST_HASH = LOWER(RAWTOHEX(STANDARD_HASH(OPERATION_ID, 'SHA256')))
 WHERE REQUEST_HASH IS NULL;

ALTER TABLE PLAN_EDIT_OPERATION
    MODIFY REQUEST_HASH NOT NULL;

ALTER TABLE PLAN_EDIT_OPERATION
    ADD CONSTRAINT CK_PLAN_OPERATION_HASH
        CHECK (LENGTH(REQUEST_HASH) = 64);

COMMIT;
