ALTER TABLE TRAVEL_PLAN
    ADD PUBLISH_STATUS VARCHAR2(10) DEFAULT 'PUBLISHED' NOT NULL;

ALTER TABLE TRAVEL_PLAN
    ADD CONSTRAINT CK_PLAN_PUBLISH_STATUS
    CHECK (PUBLISH_STATUS IN ('DRAFT', 'PUBLISHED'));

ALTER TABLE TRAVEL_PLAN
    MODIFY PUBLISH_STATUS DEFAULT 'DRAFT';

CREATE INDEX IX_TRAVEL_PLAN_PUBLISH
    ON TRAVEL_PLAN (PUBLISH_STATUS, VISIBILITY, PLAN_STATUS, UPDATED_AT DESC);
