-- Legacy schemas created from an older travelplanner_final.sql stored coordinates as VARCHAR2.
-- Run this migration only when PLAN_SCHEDULE_ITEM coordinate columns are still VARCHAR2.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET DEFINE OFF

DECLARE
    INVALID_COORDINATE_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO INVALID_COORDINATE_COUNT
      FROM PLAN_SCHEDULE_ITEM
     WHERE (LATITUDE_SNAPSHOT IS NOT NULL AND (
                NOT REGEXP_LIKE(TRIM(LATITUDE_SNAPSHOT), '^-?([0-8]?[0-9](\.[0-9]+)?|90(\.0+)?)$')
            ))
        OR (LONGITUDE_SNAPSHOT IS NOT NULL AND (
                NOT REGEXP_LIKE(TRIM(LONGITUDE_SNAPSHOT), '^-?((1[0-7][0-9]|[1-9]?[0-9])(\.[0-9]+)?|180(\.0+)?)$')
            ));

    IF INVALID_COORDINATE_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20010,
            'PLAN_SCHEDULE_ITEM contains invalid coordinate values: ' || INVALID_COORDINATE_COUNT
        );
    END IF;
END;
/

ALTER TABLE PLAN_SCHEDULE_ITEM DROP CONSTRAINT CK_PLAN_ITEM_LAT;
ALTER TABLE PLAN_SCHEDULE_ITEM DROP CONSTRAINT CK_PLAN_ITEM_LNG;

ALTER TABLE PLAN_SCHEDULE_ITEM ADD (
    LATITUDE_SNAPSHOT_NUM  NUMBER(10, 7),
    LONGITUDE_SNAPSHOT_NUM NUMBER(10, 7)
);

UPDATE PLAN_SCHEDULE_ITEM
   SET LATITUDE_SNAPSHOT_NUM = TO_NUMBER(
           TRIM(LATITUDE_SNAPSHOT),
           '999D9999999999999999',
           'NLS_NUMERIC_CHARACTERS=''.,'''
       ),
       LONGITUDE_SNAPSHOT_NUM = TO_NUMBER(
           TRIM(LONGITUDE_SNAPSHOT),
           '999D9999999999999999',
           'NLS_NUMERIC_CHARACTERS=''.,'''
       );

ALTER TABLE PLAN_SCHEDULE_ITEM DROP COLUMN LATITUDE_SNAPSHOT;
ALTER TABLE PLAN_SCHEDULE_ITEM DROP COLUMN LONGITUDE_SNAPSHOT;
ALTER TABLE PLAN_SCHEDULE_ITEM RENAME COLUMN LATITUDE_SNAPSHOT_NUM TO LATITUDE_SNAPSHOT;
ALTER TABLE PLAN_SCHEDULE_ITEM RENAME COLUMN LONGITUDE_SNAPSHOT_NUM TO LONGITUDE_SNAPSHOT;

ALTER TABLE PLAN_SCHEDULE_ITEM
    ADD CONSTRAINT CK_PLAN_ITEM_LAT
        CHECK (LATITUDE_SNAPSHOT BETWEEN -90 AND 90);

ALTER TABLE PLAN_SCHEDULE_ITEM
    ADD CONSTRAINT CK_PLAN_ITEM_LNG
        CHECK (LONGITUDE_SNAPSHOT BETWEEN -180 AND 180);

ALTER TABLE PLAN_SCHEDULE_ITEM
    ADD CONSTRAINT CK_PLAN_ITEM_VERSION
        CHECK (ITEM_VERSION >= 0);

COMMIT;
