-- Legacy schemas have both:
--   * IX_PLAN_PUBLIC_UPDATED without PUBLISH_STATUS
--   * IX_TRAVEL_PLAN_PUBLISH from 006 with the canonical public lookup columns
-- Reuse the already-valid public lookup index and build the region replacement first.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET DEFINE OFF

CREATE INDEX IX_PLAN_REGION_PUBLIC_V2
    ON TRAVEL_PLAN (
        REGION_CODE,
        PUBLISH_STATUS,
        VISIBILITY,
        PLAN_STATUS
    );

DROP INDEX IX_PLAN_PUBLIC_UPDATED;
ALTER INDEX IX_TRAVEL_PLAN_PUBLISH RENAME TO IX_PLAN_PUBLIC_UPDATED;

DROP INDEX IX_PLAN_REGION_PUBLIC;
ALTER INDEX IX_PLAN_REGION_PUBLIC_V2 RENAME TO IX_PLAN_REGION_PUBLIC;

COMMIT;
