CREATE TABLE TOUR_SYNC_STATE (
    LOCK_ID          NUMBER(1)                NOT NULL,
    RUNNING_YN       CHAR(1)                  DEFAULT 'N' NOT NULL,
    SYNC_ID          VARCHAR2(40),
    STARTED_AT       TIMESTAMP WITH TIME ZONE,
    LEASE_EXPIRES_AT TIMESTAMP WITH TIME ZONE,
    STARTED_BY       VARCHAR2(100),
    CONSTRAINT PK_TOUR_SYNC_STATE PRIMARY KEY (LOCK_ID),
    CONSTRAINT CK_TOUR_SYNC_STATE_LOCK CHECK (LOCK_ID = 1),
    CONSTRAINT CK_TOUR_SYNC_STATE_RUNNING CHECK (RUNNING_YN IN ('Y', 'N')),
    CONSTRAINT CK_TOUR_SYNC_STATE_VALUES CHECK (
        (RUNNING_YN = 'N' AND SYNC_ID IS NULL AND STARTED_AT IS NULL
            AND LEASE_EXPIRES_AT IS NULL AND STARTED_BY IS NULL)
        OR
        (RUNNING_YN = 'Y' AND SYNC_ID IS NOT NULL AND STARTED_AT IS NOT NULL
            AND LEASE_EXPIRES_AT IS NOT NULL AND STARTED_BY IS NOT NULL)
    )
);

INSERT INTO TOUR_SYNC_STATE (LOCK_ID, RUNNING_YN) VALUES (1, 'N');

CREATE TABLE TOUR_SYNC_HISTORY (
    SYNC_ID       VARCHAR2(40)                NOT NULL,
    STARTED_AT    TIMESTAMP WITH TIME ZONE    NOT NULL,
    CHANGED_COUNT NUMBER(10)                  DEFAULT 0 NOT NULL,
    FAILED_COUNT  NUMBER(10)                  DEFAULT 0 NOT NULL,
    SYNC_STATUS   VARCHAR2(20)                NOT NULL,
    MANAGER       VARCHAR2(100)               NOT NULL,
    CONSTRAINT PK_TOUR_SYNC_HISTORY PRIMARY KEY (SYNC_ID),
    CONSTRAINT CK_TOUR_SYNC_HISTORY_COUNTS CHECK (CHANGED_COUNT >= 0 AND FAILED_COUNT >= 0),
    CONSTRAINT CK_TOUR_SYNC_HISTORY_STATUS CHECK (SYNC_STATUS IN ('성공', '부분 성공', '실패'))
);

CREATE INDEX IX_TOUR_SYNC_HISTORY_STARTED
    ON TOUR_SYNC_HISTORY (SYS_EXTRACT_UTC(STARTED_AT) DESC);

COMMENT ON TABLE TOUR_SYNC_STATE IS '다중 Instance TOUR API 동기화 Lease 상태';
COMMENT ON TABLE TOUR_SYNC_HISTORY IS 'TOUR API 동기화 실행 결과 이력';

COMMIT;
