/* ============================================
   TravelPlanner DDL
   ============================================ */

/* ============================================
   1. 기존 개체 DROP
   ============================================ */

-- 테이블 DROP 
DROP TABLE REPORT_PROCESS CASCADE CONSTRAINTS;
DROP TABLE NOTIFICATION CASCADE CONSTRAINTS;
DROP TABLE REPORT CASCADE CONSTRAINTS;
DROP TABLE PLAN_SCHEDULE_ITEM CASCADE CONSTRAINTS;
DROP TABLE PLAN_DAY CASCADE CONSTRAINTS;
DROP TABLE PLAN_EDIT_OPERATION CASCADE CONSTRAINTS;
DROP TABLE PLAN_INVITATION CASCADE CONSTRAINTS;
DROP TABLE PLAN_LIKE CASCADE CONSTRAINTS;
DROP TABLE PLAN_MEMBER CASCADE CONSTRAINTS;
DROP TABLE RECENTLY_VIEWED_PLAN CASCADE CONSTRAINTS;
DROP TABLE TRAVEL_PLAN CASCADE CONSTRAINTS;
DROP TABLE GOOGLE_ACCOUNT_LINK CASCADE CONSTRAINTS;
DROP TABLE MEMBER_WARNING_SUPPRESSION CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE RECOMMEND_RULE CASCADE CONSTRAINTS;
DROP TABLE TOUR_SYNC_HISTORY CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE PLACE_MASTER CASCADE CONSTRAINTS;
DROP TABLE REGION_MASTER CASCADE CONSTRAINTS;

-- 시퀀스 DROP
DROP SEQUENCE CODE_SEQ;
DROP SEQUENCE SEQ_ADMIN;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_ITEM_NUM;
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_NEWS;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_NOTIFICATION;
DROP SEQUENCE SEQ_PLAN_DAY;
DROP SEQUENCE SEQ_PLAN_INVITATION;
DROP SEQUENCE SEQ_PLAN_LIKE;
DROP SEQUENCE SEQ_PLAN_SCHEDULE_ITEM;
DROP SEQUENCE SEQ_RECOMMEND_RULE;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_TOUR_SYNC_HISTORY;
DROP SEQUENCE SEQ_TRAVEL_PLAN;


/* ============================================
   2. 테이블 생성 (CREATE TABLE)
   ============================================ */

/* 관리자 */
CREATE TABLE ADMIN (
	ADMIN_ID NUMBER(19) NOT NULL, /* 관리자ID */
	LOGIN_ID VARCHAR2(100) NOT NULL, /* 관리자로그인ID */
	PASSWORD_HASH VARCHAR2(255) NOT NULL, /* 비밀번호해시 */
	PHONE_NUMBER VARCHAR2(20), /* 전화번호 */
	EMAIL VARCHAR2(254) NOT NULL, /* 이메일 */
	ADMIN_ROLE_CODE VARCHAR2(30) NOT NULL, /* 관리자권한코드 */
	ADMIN_STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL, /* 관리자상태 */
	CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, /* 생성일시 */
	UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 수정일시 */
);

CREATE UNIQUE INDEX PK_ADMIN
	ON ADMIN (
		ADMIN_ID ASC
	);

CREATE UNIQUE INDEX UK_ADMIN_LOGIN_ID
	ON ADMIN (
		LOGIN_ID ASC
	);

CREATE UNIQUE INDEX UK_ADMIN_EMAIL
	ON ADMIN (
		EMAIL ASC
	);

ALTER TABLE ADMIN
	ADD CONSTRAINT PK_ADMIN PRIMARY KEY (ADMIN_ID);

ALTER TABLE ADMIN
	ADD CONSTRAINT UK_ADMIN_LOGIN_ID UNIQUE (LOGIN_ID);

ALTER TABLE ADMIN
	ADD CONSTRAINT UK_ADMIN_EMAIL UNIQUE (EMAIL);

ALTER TABLE ADMIN
	ADD CONSTRAINT CK_ADMIN_STATUS CHECK (ADMIN_STATUS IN ('ACTIVE', 'INACTIVE'));

/* 구글계정 연동 */
CREATE TABLE GOOGLE_ACCOUNT_LINK (
	GOOGLE_SUBJECT VARCHAR2(255) NOT NULL, /* 구글사용자식별자 */
	MEMBER_ID NUMBER(19) NOT NULL, /* 회원ID */
	GOOGLE_EMAIL VARCHAR2(254), /* 구글이메일 */
	GOOGLE_PROFILE_IMAGE_URL VARCHAR2(1000), /* 구글프로필이미지URL */
	LINKED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 연동일시 */
);

CREATE UNIQUE INDEX PK_GOOGLE_ACCOUNT_LINK
	ON GOOGLE_ACCOUNT_LINK (
		GOOGLE_SUBJECT ASC
	);

CREATE UNIQUE INDEX UK_GOOGLE_LINK_MEMBER
	ON GOOGLE_ACCOUNT_LINK (
		MEMBER_ID ASC
	);

ALTER TABLE GOOGLE_ACCOUNT_LINK
	ADD CONSTRAINT PK_GOOGLE_ACCOUNT_LINK PRIMARY KEY (GOOGLE_SUBJECT);

ALTER TABLE GOOGLE_ACCOUNT_LINK
	ADD CONSTRAINT UK_GOOGLE_LINK_MEMBER UNIQUE (MEMBER_ID);

/* 회원 */
CREATE TABLE MEMBER (
	MEMBER_ID NUMBER(19) NOT NULL, /* 회원ID */
	MEMBER_NAME VARCHAR2(10), /* 이름 */
	EMAIL VARCHAR2(255) NOT NULL, /* 이메일 */
	NICKNAME VARCHAR2(50) NOT NULL, /* 닉네임 */
	PASSWORD_HASH VARCHAR2(255), /* 비밀번호해시 */
	BIRTH_DATE DATE, /* 생년월일 */
	GENDER_CODE VARCHAR2(20), /* 성별코드 */
	PHONE_NUMBER VARCHAR2(20), /* 전화번호 */
	PROFILE_IMAGE_URL VARCHAR2(1000), /* 프로필이미지URL */
	PRIVACY_CONSENT_YN CHAR(1) DEFAULT 'N' NOT NULL, /* 개인정보동의여부 */
	MEMBER_STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL, /* 회원상태 */
	CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, /* 생성일시 */
	UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, /* 수정일시 */
	WITHDRAWN_AT TIMESTAMP(6) WITH TIME ZONE /* 탈퇴일시 */
);

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		MEMBER_ID ASC
	);

CREATE UNIQUE INDEX UK_MEMBER_EMAIL
	ON MEMBER (
		EMAIL ASC
	);

ALTER TABLE MEMBER
	ADD CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID);

ALTER TABLE MEMBER
	ADD CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL);

ALTER TABLE MEMBER
	ADD CONSTRAINT CK_MEMBER_CONSENT CHECK (PRIVACY_CONSENT_YN IN ('Y', 'N'));

ALTER TABLE MEMBER
	ADD CONSTRAINT CK_MEMBER_STATUS CHECK (MEMBER_STATUS IN ('ACTIVE', 'WITHDRAWN'));

/* 회원 경고 숨김 설정 */
CREATE TABLE MEMBER_WARNING_SUPPRESSION (
	MEMBER_ID NUMBER(19) NOT NULL, /* 회원ID */
	WARNING_TYPE VARCHAR2(30) NOT NULL, /* 경고유형 */
	SUPPRESSED_DATE DATE NOT NULL, /* 숨김적용일 */
	UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 수정일시 */
);

CREATE UNIQUE INDEX PK_WARNING_SUPPRESSION
	ON MEMBER_WARNING_SUPPRESSION (
		MEMBER_ID ASC,
		WARNING_TYPE ASC
	);

CREATE INDEX IX_WARNING_SUPPRESSED_DATE
	ON MEMBER_WARNING_SUPPRESSION (
		MEMBER_ID ASC,
		WARNING_TYPE ASC,
		SUPPRESSED_DATE ASC
	);

ALTER TABLE MEMBER_WARNING_SUPPRESSION
	ADD CONSTRAINT PK_WARNING_SUPPRESSION PRIMARY KEY (MEMBER_ID, WARNING_TYPE);

ALTER TABLE MEMBER_WARNING_SUPPRESSION
	ADD CONSTRAINT CK_WARNING_TYPE CHECK (WARNING_TYPE IN ('PERIOD_SHORTEN_DELETE', 'SCHEDULE_ITEM_DELETE'));

/* 공지사항 */
CREATE TABLE NOTICE (
	NOTICE_ID NUMBER(19) NOT NULL, /* 공지사항ID */
	ADMIN_ID NUMBER(19) NOT NULL, /* 관리자ID */
	TITLE VARCHAR2(200) NOT NULL, /* 제목 */
	CONTENT CLOB NOT NULL, /* 내용 */
	VIEW_COUNT NUMBER(10) DEFAULT 0 NOT NULL, /* 조회수 */
	CATEGORY_CODE VARCHAR2(30) NOT NULL, /* 카테고리코드 */
	HIDDEN_YN CHAR(1) DEFAULT 'N' NOT NULL, /* 숨김여부 */
	CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 생성일시 */
);

CREATE UNIQUE INDEX PK_NOTICE
	ON NOTICE (
		NOTICE_ID ASC
	);

ALTER TABLE NOTICE
	ADD CONSTRAINT PK_NOTICE PRIMARY KEY (NOTICE_ID);

ALTER TABLE NOTICE
	ADD CONSTRAINT CK_NOTICE_HIDDEN CHECK (HIDDEN_YN IN ('Y', 'N'));

/* 알림 */
CREATE TABLE NOTIFICATION (
	NOTIFICATION_ID NUMBER(19) NOT NULL, /* 알림ID */
	RECIPIENT_MEMBER_ID NUMBER(19), /* 수신자ID */
	NOTIFICATION_TYPE VARCHAR2(30) NOT NULL, /* 알림유형 */
	TITLE VARCHAR2(200) NOT NULL, /* 제목 */
	CONTENT CLOB NOT NULL, /* 내용 */
	RELATED_REPORT_ID NUMBER(19), /* 관련신고ID */
	READ_YN CHAR(1) DEFAULT 'Y' NOT NULL, /* 확인여부 */
	CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 생성일시 */
);

CREATE UNIQUE INDEX PK_NOTIFICATION
	ON NOTIFICATION (
		NOTIFICATION_ID ASC
	);

CREATE INDEX IX_NOTIFICATION_REPORT
	ON NOTIFICATION (
		RELATED_REPORT_ID ASC
	);

ALTER TABLE NOTIFICATION
	ADD CONSTRAINT PK_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID);

ALTER TABLE NOTIFICATION
	ADD CONSTRAINT CK_NOTIFICATION_READ_YN CHECK (READ_YN IN ('Y', 'N'));

/* 여행장소기본정보 */
CREATE TABLE PLACE_MASTER (
	PLACE_PROVIDER VARCHAR2(30) NOT NULL, /* 장소제공자 */
	EXTERNAL_PLACE_ID VARCHAR2(100) NOT NULL, /* 외부장소ID */
	PLACE_TYPE VARCHAR2(30) NOT NULL, /* 장소유형 */
	PLACE_NAME VARCHAR2(200) NOT NULL, /* 장소명 */
	CATEGORY_NAME VARCHAR2(100), /* 카테고리명 */
	ADDRESS VARCHAR2(500), /* 주소 */
	DESCRIPTION CLOB, /* 설명 */
	LATITUDE NUMBER(10, 7), /* 위도 */
	LONGITUDE NUMBER(10, 7), /* 경도 */
	IMAGE_URL VARCHAR2(1000), /* 이미지URL */
	ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL, /* 사용여부 */
	SYNCED_AT TIMESTAMP(6) WITH TIME ZONE, /* 동기화일시 */
	UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 수정일시 */
);

CREATE UNIQUE INDEX PK_PLACE_MASTER
	ON PLACE_MASTER (
		PLACE_PROVIDER ASC,
		EXTERNAL_PLACE_ID ASC
	);

CREATE INDEX IX_PLACE_NAME_ACTIVE
	ON PLACE_MASTER (
		PLACE_NAME ASC,
		ACTIVE_YN ASC
	);

ALTER TABLE PLACE_MASTER
	ADD CONSTRAINT PK_PLACE_MASTER PRIMARY KEY (PLACE_PROVIDER, EXTERNAL_PLACE_ID);

ALTER TABLE PLACE_MASTER
	ADD CONSTRAINT CK_PLACE_ACTIVE CHECK (ACTIVE_YN IN ('Y', 'N'));

ALTER TABLE PLACE_MASTER
	ADD CONSTRAINT CK_PLACE_LATITUDE CHECK (LATITUDE BETWEEN -90 AND 90);

ALTER TABLE PLACE_MASTER
	ADD CONSTRAINT CK_PLACE_LONGITUDE CHECK (LONGITUDE BETWEEN -180 AND 180);

/* 여행일차 */
CREATE TABLE PLAN_DAY (
	PLAN_DAY_ID NUMBER(19) NOT NULL, /* 여행일차ID */
	PLAN_ID NUMBER(19) NOT NULL, /* 여행플랜ID */
	DAY_NO NUMBER(2) NOT NULL, /* 일차번호 */
	TRAVEL_DATE DATE NOT NULL, /* 여행일자 */
	SCHEDULE_VERSION NUMBER(10) DEFAULT 0 NOT NULL /* 일정버전번호 */
);

CREATE UNIQUE INDEX PK_PLAN_DAY
	ON PLAN_DAY (
		PLAN_DAY_ID ASC
	);

CREATE UNIQUE INDEX UK_PLAN_DAY_NO
	ON PLAN_DAY (
		PLAN_ID ASC,
		DAY_NO ASC
	);

CREATE UNIQUE INDEX UK_PLAN_DAY_DATE
	ON PLAN_DAY (
		PLAN_ID ASC,
		TRAVEL_DATE ASC
	);

ALTER TABLE PLAN_DAY
	ADD CONSTRAINT PK_PLAN_DAY PRIMARY KEY (PLAN_DAY_ID);

ALTER TABLE PLAN_DAY
	ADD CONSTRAINT UK_PLAN_DAY_NO UNIQUE (PLAN_ID, DAY_NO);

ALTER TABLE PLAN_DAY
	ADD CONSTRAINT UK_PLAN_DAY_DATE UNIQUE (PLAN_ID, TRAVEL_DATE);

ALTER TABLE PLAN_DAY
	ADD CONSTRAINT CK_PLAN_DAY_NO CHECK (DAY_NO BETWEEN 1 AND 14);

/* 플랜편집작업 */
CREATE TABLE PLAN_EDIT_OPERATION (
	OPERATION_ID VARCHAR2(36) NOT NULL, /* 편집작업ID */
	PLAN_ID NUMBER(19) NOT NULL, /* 여행플랜ID */
	MEMBER_ID NUMBER(19) NOT NULL, /* 회원ID */
	OPERATION_TYPE VARCHAR2(10) NOT NULL, /* 작업유형 */
	TARGET_ITEM_ID NUMBER(19), /* 대상일정항목 */
	BASE_VERSION NUMBER(10), /* 기준버전번호 */
	RESULT_VERSION NUMBER(10), /* 결과버전번호 */
	CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 생성일시 */
);

CREATE UNIQUE INDEX PK_PLAN_EDIT_OPERATION
	ON PLAN_EDIT_OPERATION (
		OPERATION_ID ASC
	);

CREATE INDEX IX_PLAN_OPERATION_CREATED
	ON PLAN_EDIT_OPERATION (
		PLAN_ID ASC,
		SYS_EXTRACT_UTC(CREATED_AT) ASC
	);

ALTER TABLE PLAN_EDIT_OPERATION
	ADD CONSTRAINT PK_PLAN_EDIT_OPERATION PRIMARY KEY (OPERATION_ID);

ALTER TABLE PLAN_EDIT_OPERATION
	ADD CONSTRAINT CK_PLAN_OPERATION_TYPE CHECK (OPERATION_TYPE IN ('ADD', 'UPDATE', 'DELETE', 'MOVE', 'REORDER'));

/* 플랜초대 */
CREATE TABLE PLAN_INVITATION (
	INVITATION_ID NUMBER(19) NOT NULL, /* 초대ID */
	PLAN_ID NUMBER(19) NOT NULL, /* 여행플랜ID */
	INVITER_MEMBER_ID NUMBER(19) NOT NULL, /* 초대자회원ID */
	INVITEE_MEMBER_ID NUMBER(19), /* 피초대회원ID */
	INVITEE_EMAIL VARCHAR2(254) NOT NULL, /* 피초대이메일 */
	INVITATION_STATUS VARCHAR2(10) DEFAULT 'PENDING' NOT NULL, /* 초대상태 */
	INVITATION_TOKEN VARCHAR2(128) NOT NULL, /* 초대토큰 */
	EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, /* 만료일시 */
	RESPONDED_AT TIMESTAMP(6) WITH TIME ZONE, /* 응답일시 */
	CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 생성일시 */
);

CREATE UNIQUE INDEX PK_PLAN_INVITATION
	ON PLAN_INVITATION (
		INVITATION_ID ASC
	);

CREATE UNIQUE INDEX UK_PLAN_INVITATION_TOKEN
	ON PLAN_INVITATION (
		INVITATION_TOKEN ASC
	);

CREATE INDEX IX_INVITE_EMAIL_STATUS
	ON PLAN_INVITATION (
		INVITEE_EMAIL ASC,
		INVITATION_STATUS ASC
	);

CREATE INDEX IX_INVITE_MEMBER_STATUS
	ON PLAN_INVITATION (
		INVITEE_MEMBER_ID ASC,
		INVITATION_STATUS ASC
	);

ALTER TABLE PLAN_INVITATION
	ADD CONSTRAINT PK_PLAN_INVITATION PRIMARY KEY (INVITATION_ID);

ALTER TABLE PLAN_INVITATION
	ADD CONSTRAINT UK_PLAN_INVITATION_TOKEN UNIQUE (INVITATION_TOKEN);

ALTER TABLE PLAN_INVITATION
	ADD CONSTRAINT CK_INVITATION_STATUS CHECK (INVITATION_STATUS IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELED'));

ALTER TABLE PLAN_INVITATION
	ADD CONSTRAINT CK_INVITATION_EXPIRY CHECK (EXPIRES_AT > CREATED_AT);

/* 회원 여행플랜 좋아요 */
CREATE TABLE PLAN_LIKE (
	PLAN_LIKE_ID NUMBER(19) NOT NULL, /* 좋아요ID */
	PLAN_ID NUMBER(19) NOT NULL, /* 여행플랜ID */
	MEMBER_ID NUMBER(19) NOT NULL, /* 회원ID */
	CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 생성일시 */
);

CREATE UNIQUE INDEX PK_PLAN_LIKE
	ON PLAN_LIKE (
		PLAN_LIKE_ID ASC
	);

CREATE UNIQUE INDEX UK_PLAN_LIKE_MEMBER
	ON PLAN_LIKE (
		PLAN_ID ASC,
		MEMBER_ID ASC
	);

ALTER TABLE PLAN_LIKE
	ADD CONSTRAINT PK_PLAN_LIKE PRIMARY KEY (PLAN_LIKE_ID);

ALTER TABLE PLAN_LIKE
	ADD CONSTRAINT UK_PLAN_LIKE_MEMBER UNIQUE (PLAN_ID, MEMBER_ID);

/* 플랜참여자 */
CREATE TABLE PLAN_MEMBER (
	PLAN_ID NUMBER(19) NOT NULL, /* 여행플랜ID */
	MEMBER_ID NUMBER(19) NOT NULL, /* 회원ID */
	PARTICIPANT_TYPE VARCHAR2(10) NOT NULL, /* 참여자유형 */
	JOINED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 참여일시 */
);

CREATE UNIQUE INDEX PK_PLAN_MEMBER
	ON PLAN_MEMBER (
		PLAN_ID ASC,
		MEMBER_ID ASC
	);

CREATE INDEX IX_PLAN_MEMBER_MEMBER
	ON PLAN_MEMBER (
		PLAN_ID ASC,
		MEMBER_ID ASC
	);

ALTER TABLE PLAN_MEMBER
	ADD CONSTRAINT PK_PLAN_MEMBER PRIMARY KEY (PLAN_ID, MEMBER_ID);

/* 플랜일정항목 */
CREATE TABLE PLAN_SCHEDULE_ITEM (
	SCHEDULE_ITEM_ID NUMBER(19) NOT NULL, /* 일정항목ID */
	PLAN_DAY_ID NUMBER(19) NOT NULL, /* 여행일차ID */
	TIME_SLOT VARCHAR2(10) DEFAULT 'MORNING' NOT NULL, /* 시간대 */
	POSITION_NO NUMBER(4) NOT NULL, /* 표시순서 */
	PLACE_PROVIDER VARCHAR2(30) NOT NULL, /* 장소제공자 */
	EXTERNAL_PLACE_ID VARCHAR2(100) NOT NULL, /* 외부장소ID */
	PLACE_NAME_SNAPSHOT VARCHAR2(200) NOT NULL, /* 장소명스냅샷 */
	CATEGORY_SNAPSHOT VARCHAR2(100), /* 카테고리스냅샷 */
	ADDRESS_SNAPSHOT VARCHAR2(500), /* 주소스냅샷 */
	LATITUDE_SNAPSHOT VARCHAR2(20), /* 위도스냅샷 */
	LONGITUDE_SNAPSHOT VARCHAR2(20), /* 경도스냅샷 */
	IMAGE_URL_SNAPSHOT VARCHAR2(1000), /* 이미지URL스냅샷 */
	DESCRIPTION_SNAPSHOT CLOB, /* 설명스냅샷 */
	ITEM_VERSION NUMBER(10) DEFAULT 0 NOT NULL, /* 항목버전번호 */
	CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, /* 생성일시 */
	UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 수정일시 */
);

CREATE UNIQUE INDEX PK_PLAN_SCHEDULE_ITEM
	ON PLAN_SCHEDULE_ITEM (
		SCHEDULE_ITEM_ID ASC
	);

CREATE UNIQUE INDEX UK_PLAN_ITEM_PLACE_SLOT
	ON PLAN_SCHEDULE_ITEM (
		PLAN_DAY_ID ASC,
		TIME_SLOT ASC,
		PLACE_PROVIDER ASC,
		EXTERNAL_PLACE_ID ASC
	);

CREATE INDEX UK_PLAN_ITEM_POSITION
	ON PLAN_SCHEDULE_ITEM (
		PLAN_DAY_ID ASC,
		TIME_SLOT ASC,
		POSITION_NO ASC
	);

ALTER TABLE PLAN_SCHEDULE_ITEM
	ADD CONSTRAINT PK_PLAN_SCHEDULE_ITEM PRIMARY KEY (SCHEDULE_ITEM_ID);

ALTER TABLE PLAN_SCHEDULE_ITEM
	ADD CONSTRAINT UK_PLAN_ITEM_POSITION UNIQUE (PLAN_DAY_ID, TIME_SLOT, POSITION_NO);

ALTER TABLE PLAN_SCHEDULE_ITEM
	ADD CONSTRAINT UK_PLAN_ITEM_PLACE_SLOT UNIQUE (PLAN_DAY_ID, TIME_SLOT, PLACE_PROVIDER, EXTERNAL_PLACE_ID);

ALTER TABLE PLAN_SCHEDULE_ITEM
	ADD CONSTRAINT CK_PLAN_ITEM_TIME CHECK (TIME_SLOT IN ('MORNING', 'AFTERNOON'));

ALTER TABLE PLAN_SCHEDULE_ITEM
	ADD CONSTRAINT CK_PLAN_ITEM_POSITION CHECK (POSITION_NO >= 1);

ALTER TABLE PLAN_SCHEDULE_ITEM
	ADD CONSTRAINT CK_PLAN_ITEM_LAT CHECK (LATITUDE_SNAPSHOT IS NULL OR REGEXP_LIKE(LATITUDE_SNAPSHOT, '^-?([0-8]?[0-9](\.[0-9]+)?|90(\.0+)?)$'));

ALTER TABLE PLAN_SCHEDULE_ITEM
	ADD CONSTRAINT CK_PLAN_ITEM_LNG CHECK (LONGITUDE_SNAPSHOT IS NULL OR REGEXP_LIKE(LONGITUDE_SNAPSHOT, '^-?((1[0-7][0-9]|[1-9]?[0-9])(\.[0-9]+)?|180(\.0+)?)$'));

/* 최근조회플랜 */
CREATE TABLE RECENTLY_VIEWED_PLAN (
	PLAN_ID NUMBER(19) NOT NULL, /* 여행플랜ID */
	MEMBER_ID NUMBER(19) NOT NULL, /* 회원ID */
	VIEWED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 조회일시 */
);

CREATE UNIQUE INDEX PK_RECENTLY_VIEWED_PLAN
	ON RECENTLY_VIEWED_PLAN (
		PLAN_ID ASC,
		MEMBER_ID ASC
	);

ALTER TABLE RECENTLY_VIEWED_PLAN
	ADD CONSTRAINT PK_RECENTLY_VIEWED_PLAN PRIMARY KEY (PLAN_ID, MEMBER_ID);

/* 추천규칙 */
CREATE TABLE RECOMMEND_RULE (
	RULE_ID NUMBER(19) NOT NULL, /* 추천규칙ID */
	LIKE_WEIGHT NUMBER(8, 4) DEFAULT 0 NOT NULL, /* 좋아요가중치 */
	VIEW_WEIGHT NUMBER(8, 4) DEFAULT 0 NOT NULL, /* 조회수가중치 */
	COPY_WEIGHT NUMBER(8, 4) DEFAULT 0 NOT NULL, /* 플랜복사가중치 */
	ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL, /* 사용여부 */
	ADMIN_ID NUMBER(19) NOT NULL, /* 관리자ID */
	CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, /* 생성일시 */
	UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 수정일시 */
);

CREATE UNIQUE INDEX PK_RECOMMEND_RULE
	ON RECOMMEND_RULE (
		RULE_ID ASC
	);

ALTER TABLE RECOMMEND_RULE
	ADD CONSTRAINT PK_RECOMMEND_RULE PRIMARY KEY (RULE_ID);

ALTER TABLE RECOMMEND_RULE
	ADD CONSTRAINT CK_RECOMMEND_RULE_ACTIVE CHECK (ACTIVE_YN IN ('Y', 'N'));

/* 국내여행지역 기준정보 */
CREATE TABLE REGION_MASTER (
	REGION_CODE VARCHAR2(20) NOT NULL, /* 지역코드 */
	REGION_NAME VARCHAR2(100) NOT NULL, /* 지역명 */
	PARENT_REGION_CODE VARCHAR2(20), /* 상위지역코드 */
	REGION_LEVEL VARCHAR2(10) NOT NULL, /* 지역계층 */
	DISPLAY_ORDER NUMBER(5) DEFAULT 0 NOT NULL, /* 표시순서 */
	ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL /* 사용여부 */
);

CREATE UNIQUE INDEX PK_REGION_MASTER
	ON REGION_MASTER (
		REGION_CODE ASC
	);

CREATE INDEX IX_REGION_NAME_ACTIVE
	ON REGION_MASTER (
		REGION_NAME ASC,
		ACTIVE_YN ASC
	);

CREATE INDEX IX_REGION_PARENT_NAME
	ON REGION_MASTER (
		REGION_NAME ASC,
		PARENT_REGION_CODE ASC
	);

ALTER TABLE REGION_MASTER
	ADD CONSTRAINT PK_REGION_MASTER PRIMARY KEY (REGION_CODE);

ALTER TABLE REGION_MASTER
	ADD CONSTRAINT CK_REGION_LEVEL CHECK (REGION_LEVEL IN ('SIDO', 'SIGUNGU'));

ALTER TABLE REGION_MASTER
	ADD CONSTRAINT CK_REGION_ACTIVE CHECK (ACTIVE_YN IN ('Y', 'N'));

ALTER TABLE REGION_MASTER
	ADD CONSTRAINT CK_REGION_PARENT CHECK (
		(REGION_LEVEL = 'SIDO' AND PARENT_REGION_CODE IS NULL)
		OR (REGION_LEVEL = 'SIGUNGU' AND PARENT_REGION_CODE IS NOT NULL)
	);

/* 플랜신고 */
CREATE TABLE REPORT (
	REPORT_ID NUMBER(19) NOT NULL, /* 신고ID */
	PLAN_ID NUMBER(19) NOT NULL, /* 여행플랜ID */
	REPORTER_MEMBER_ID NUMBER(19) NOT NULL, /* 신고자회원ID */
	REASON_CODE VARCHAR2(30) NOT NULL, /* 신고사유코드 */
	REASON_DETAIL VARCHAR2(1000), /* 신고상세사유 */
	REPORT_STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL, /* 신고상태 */
	CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 생성일시 */
);

CREATE UNIQUE INDEX PK_REPORT
	ON REPORT (
		REPORT_ID ASC
	);

CREATE INDEX IX_REPORT_PLAN_CREATED
	ON REPORT (
		PLAN_ID ASC,
		SYS_EXTRACT_UTC(CREATED_AT) ASC
	);

ALTER TABLE REPORT
	ADD CONSTRAINT PK_REPORT PRIMARY KEY (REPORT_ID);

ALTER TABLE REPORT
	ADD CONSTRAINT CK_REPORT_STATUS CHECK (REPORT_STATUS IN ('PENDING', 'IN_PROGRESS', 'RESOLVED', 'REJECTED'));

/* 신고처리 */
CREATE TABLE REPORT_PROCESS (
	REPORT_ID NUMBER(19) NOT NULL, /* 신고ID */
	PROCESSOR_ADMIN_ID NUMBER(19) NOT NULL, /* 처리관리자ID */
	PROCESS_RESULT_CODE VARCHAR2(30) NOT NULL, /* 처리결과코드 */
	PROCESS_REASON VARCHAR2(1000), /* 처리사유 */
	PROCESSED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL /* 처리일시 */
);

CREATE UNIQUE INDEX PK_REPORT_PROCESS
	ON REPORT_PROCESS (
		REPORT_ID ASC
	);

ALTER TABLE REPORT_PROCESS
	ADD CONSTRAINT PK_REPORT_PROCESS PRIMARY KEY (REPORT_ID);

/* 관광정보 동기화 이력 */
CREATE TABLE TOUR_SYNC_HISTORY (
	SYNC_HISTORY_ID NUMBER(19) NOT NULL, /* 동기화이력ID */
	ADMIN_ID NUMBER(19) NOT NULL, /* 관리자ID */
	PROVIDER_CODE VARCHAR2(30) NOT NULL, /* 제공자코드 */
	STARTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL, /* 시작일시 */
	FINISHED_AT TIMESTAMP(6) WITH TIME ZONE, /* 종료일시 */
	TOTAL_COUNT NUMBER(10) DEFAULT 0 NOT NULL, /* 전체건수 */
	INSERT_COUNT NUMBER(10) DEFAULT 0 NOT NULL, /* 등록건수 */
	UPDATE_COUNT NUMBER(10) DEFAULT 0 NOT NULL, /* 수정건수 */
	SUCCESS_COUNT NUMBER(10) DEFAULT 0 NOT NULL, /* 성공건수 */
	FAIL_COUNT NUMBER(10) DEFAULT 0 NOT NULL, /* 실패건수 */
	ERROR_MESSAGE CLOB, /* 오류내용 */
	PROCESS_STATUS VARCHAR2(20) NOT NULL /* 처리상태 */
);

CREATE UNIQUE INDEX PK_TOUR_SYNC_HISTORY
	ON TOUR_SYNC_HISTORY (
		SYNC_HISTORY_ID ASC
	);

ALTER TABLE TOUR_SYNC_HISTORY
	ADD CONSTRAINT PK_TOUR_SYNC_HISTORY PRIMARY KEY (SYNC_HISTORY_ID);

ALTER TABLE TOUR_SYNC_HISTORY
	ADD CONSTRAINT CK_TOUR_SYNC_COUNT CHECK (
		TOTAL_COUNT >= 0 AND INSERT_COUNT >= 0 AND UPDATE_COUNT >= 0
		AND SUCCESS_COUNT >= 0 AND FAIL_COUNT >= 0
	);

/* 여행플랜 */
CREATE TABLE TRAVEL_PLAN (
	PLAN_ID NUMBER(19) NOT NULL, /* 여행플랜ID */
	SOURCE_PLAN_ID NUMBER(19), /* 원본여행플랜ID */
	OWNER_MEMBER_ID NUMBER(19) NOT NULL, /* 생성자회원ID */
	TITLE VARCHAR2(200) NOT NULL, /* 여행제목 */
	REGION_CODE VARCHAR2(20) NOT NULL, /* 여행지역코드 */
	START_DATE DATE NOT NULL, /* 여행시작일 */
	END_DATE DATE NOT NULL, /* 여행종료일 */
	VISIBILITY VARCHAR2(10) DEFAULT 'PUBLIC' NOT NULL, /* 공개범위 */
	PLAN_STATUS VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL, /* 플랜상태 */
	VERSION_NO NUMBER(10) DEFAULT 0 NOT NULL, /* 버전번호 */
	DELETED_AT TIMESTAMP(6) WITH TIME ZONE, /* 삭제일시 */
	THUMBNAIL_IMG VARCHAR2(1000), /* 대표이미지 */
	DELETED_BY_MEMBER_ID NUMBER(19), /* 삭제회원ID */
	RESTORED_AT TIMESTAMP(6) WITH TIME ZONE, /* 복구일시 */
	RESTORED_BY_ADMIN_ID NUMBER(19), /* 복구관리자ID */
	CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, /* 생성일시 */
	UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, /* 수정일시 */
	VIEW_COUNT NUMBER(6) DEFAULT 0 NOT NULL /* 조회수 */
);

CREATE UNIQUE INDEX PK_TRAVEL_PLAN
	ON TRAVEL_PLAN (
		PLAN_ID ASC
	);

CREATE INDEX IX_PLAN_OWNER_UPDATED
	ON TRAVEL_PLAN (
		OWNER_MEMBER_ID ASC,
		SYS_EXTRACT_UTC(UPDATED_AT) ASC
	);

CREATE INDEX IX_PLAN_PUBLIC_UPDATED
	ON TRAVEL_PLAN (
		VISIBILITY ASC,
		PLAN_STATUS ASC,
		SYS_EXTRACT_UTC(UPDATED_AT) ASC
	);

CREATE INDEX IX_PLAN_REGION_PUBLIC
	ON TRAVEL_PLAN (
		REGION_CODE ASC,
		VISIBILITY ASC,
		PLAN_STATUS ASC
	);

ALTER TABLE TRAVEL_PLAN
	ADD CONSTRAINT PK_TRAVEL_PLAN PRIMARY KEY (PLAN_ID);

ALTER TABLE TRAVEL_PLAN
	ADD CONSTRAINT CK_PLAN_VISIBILITY CHECK (VISIBILITY IN ('PUBLIC', 'PRIVATE'));

ALTER TABLE TRAVEL_PLAN
	ADD CONSTRAINT CK_PLAN_STATUS CHECK (PLAN_STATUS IN ('ACTIVE', 'DELETED'));

ALTER TABLE TRAVEL_PLAN
	ADD CONSTRAINT CK_PLAN_DATE_RANGE CHECK (START_DATE <= END_DATE);

ALTER TABLE TRAVEL_PLAN
	ADD CONSTRAINT CK_PLAN_DURATION CHECK ((END_DATE - START_DATE) BETWEEN 0 AND 13);

ALTER TABLE TRAVEL_PLAN
	ADD CONSTRAINT CK_PLAN_DELETE_STATE CHECK (
		(PLAN_STATUS = 'ACTIVE' AND DELETED_AT IS NULL AND DELETED_BY_MEMBER_ID IS NULL)
		OR (PLAN_STATUS = 'DELETED' AND DELETED_AT IS NOT NULL AND DELETED_BY_MEMBER_ID IS NOT NULL)
	);

/* Foreign Keys */
ALTER TABLE GOOGLE_ACCOUNT_LINK
	ADD CONSTRAINT FK_GOOGLE_LINK_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE MEMBER_WARNING_SUPPRESSION
	ADD CONSTRAINT FK_WARNING_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE NOTICE
	ADD CONSTRAINT FK_NOTICE_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN (ADMIN_ID);

ALTER TABLE NOTIFICATION
	ADD CONSTRAINT FK_NOTIFICATION_REPORT FOREIGN KEY (RELATED_REPORT_ID) REFERENCES REPORT (REPORT_ID);

ALTER TABLE PLAN_DAY
	ADD CONSTRAINT FK_PLAN_DAY_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID);

ALTER TABLE PLAN_EDIT_OPERATION
	ADD CONSTRAINT FK_PLAN_OPERATION_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID);

ALTER TABLE PLAN_EDIT_OPERATION
	ADD CONSTRAINT FK_PLAN_OPERATION_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE PLAN_INVITATION
	ADD CONSTRAINT FK_INVITATION_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID);

ALTER TABLE PLAN_INVITATION
	ADD CONSTRAINT FK_INVITATION_INVITER FOREIGN KEY (INVITER_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE PLAN_INVITATION
	ADD CONSTRAINT FK_INVITATION_INVITEE FOREIGN KEY (INVITEE_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE PLAN_LIKE
	ADD CONSTRAINT FK_PLAN_LIKE_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID);

ALTER TABLE PLAN_LIKE
	ADD CONSTRAINT FK_PLAN_LIKE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE PLAN_MEMBER
	ADD CONSTRAINT FK_PLAN_MEMBER_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID);

ALTER TABLE PLAN_MEMBER
	ADD CONSTRAINT FK_PLAN_MEMBER_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE PLAN_SCHEDULE_ITEM
	ADD CONSTRAINT FK_PLAN_ITEM_DAY FOREIGN KEY (PLAN_DAY_ID) REFERENCES PLAN_DAY (PLAN_DAY_ID);

ALTER TABLE RECENTLY_VIEWED_PLAN
	ADD CONSTRAINT FK_RECENT_PLAN_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID);

ALTER TABLE RECENTLY_VIEWED_PLAN
	ADD CONSTRAINT FK_RECENT_PLAN_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE RECOMMEND_RULE
	ADD CONSTRAINT FK_RULE_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN (ADMIN_ID);

ALTER TABLE REGION_MASTER
	ADD CONSTRAINT FK_REGION_PARENT FOREIGN KEY (PARENT_REGION_CODE) REFERENCES REGION_MASTER (REGION_CODE);

ALTER TABLE REPORT
	ADD CONSTRAINT FK_REPORT_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID);

ALTER TABLE REPORT
	ADD CONSTRAINT FK_REPORT_MEMBER FOREIGN KEY (REPORTER_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE REPORT_PROCESS
	ADD CONSTRAINT FK_REPORT_PROCESS_REPORT FOREIGN KEY (REPORT_ID) REFERENCES REPORT (REPORT_ID);

ALTER TABLE REPORT_PROCESS
	ADD CONSTRAINT FK_REPORT_PROCESS_ADMIN FOREIGN KEY (PROCESSOR_ADMIN_ID) REFERENCES ADMIN (ADMIN_ID);

ALTER TABLE TOUR_SYNC_HISTORY
	ADD CONSTRAINT FK_TOUR_SYNC_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN (ADMIN_ID);

ALTER TABLE TRAVEL_PLAN
	ADD CONSTRAINT FK_PLAN_OWNER FOREIGN KEY (OWNER_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE TRAVEL_PLAN
	ADD CONSTRAINT FK_PLAN_REGION FOREIGN KEY (REGION_CODE) REFERENCES REGION_MASTER (REGION_CODE);

ALTER TABLE TRAVEL_PLAN
	ADD CONSTRAINT FK_PLAN_DELETED_MEMBER FOREIGN KEY (DELETED_BY_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE TRAVEL_PLAN
	ADD CONSTRAINT FK_PLAN_RESTORED_ADMIN FOREIGN KEY (RESTORED_BY_ADMIN_ID) REFERENCES ADMIN (ADMIN_ID);


/* ============================================
   3. 시퀀스 생성 (CREATE SEQUENCE - 16개)
   ============================================ */

CREATE SEQUENCE CODE_SEQ
	START WITH 9
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 99999999
	NOCACHE;

CREATE SEQUENCE SEQ_ADMIN
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_BOARD
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_ITEM_NUM
	START WITH 21
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 99999999
	CACHE 20;

CREATE SEQUENCE SEQ_MEMBER
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_NEWS
	START WITH 21
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 999999
	CACHE 20;

CREATE SEQUENCE SEQ_NOTICE
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_NOTIFICATION
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_PLAN_DAY
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_PLAN_INVITATION
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_PLAN_LIKE
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_PLAN_SCHEDULE_ITEM
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_RECOMMEND_RULE
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_REPORT
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_TOUR_SYNC_HISTORY
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;

CREATE SEQUENCE SEQ_TRAVEL_PLAN
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	CACHE 20;