-- Local development schema. Oracle DDL under docs/database/ddl remains authoritative.

CREATE TABLE REGION_MASTER (
    REGION_CODE        VARCHAR2(20)  NOT NULL,
    REGION_NAME        VARCHAR2(100) NOT NULL,
    PARENT_REGION_CODE VARCHAR2(20),
    REGION_LEVEL       VARCHAR2(10)  NOT NULL,
    DISPLAY_ORDER      NUMBER(5)     DEFAULT 0 NOT NULL,
    ACTIVE_YN          CHAR(1)       DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_REGION_MASTER PRIMARY KEY (REGION_CODE),
    CONSTRAINT FK_REGION_PARENT
        FOREIGN KEY (PARENT_REGION_CODE) REFERENCES REGION_MASTER (REGION_CODE),
    CONSTRAINT CK_REGION_LEVEL
        CHECK (REGION_LEVEL IN ('SIDO', 'SIGUNGU')),
    CONSTRAINT CK_REGION_ACTIVE
        CHECK (ACTIVE_YN IN ('Y', 'N')),
    CONSTRAINT CK_REGION_PARENT
        CHECK (
            (REGION_LEVEL = 'SIDO' AND PARENT_REGION_CODE IS NULL)
            OR (REGION_LEVEL = 'SIGUNGU' AND PARENT_REGION_CODE IS NOT NULL)
        )
);
