-- Local development schema. Oracle DDL under docs/database/ddl remains authoritative.

CREATE TABLE REGION_MASTER (
    REGION_CODE        VARCHAR2(20)  NOT NULL,
    REGION_NAME        VARCHAR2(100) NOT NULL,
    PARENT_REGION_CODE VARCHAR2(20),
    REGION_LEVEL       VARCHAR2(10)  NOT NULL,
    DISPLAY_ORDER      NUMBER(5)     DEFAULT 0 NOT NULL,
    ACTIVE_YN          CHAR(1)       DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_REGION_MASTER PRIMARY KEY (REGION_CODE),
    CONSTRAINT FK_REGION_PARENT
        FOREIGN KEY (PARENT_REGION_CODE) REFERENCES REGION_MASTER (REGION_CODE),
    CONSTRAINT CK_REGION_LEVEL
        CHECK (REGION_LEVEL IN ('SIDO', 'SIGUNGU')),
    CONSTRAINT CK_REGION_ACTIVE
        CHECK (ACTIVE_YN IN ('Y', 'N')),
    CONSTRAINT CK_REGION_PARENT
        CHECK (
            (REGION_LEVEL = 'SIDO' AND PARENT_REGION_CODE IS NULL)
            OR (REGION_LEVEL = 'SIGUNGU' AND PARENT_REGION_CODE IS NOT NULL)
        )
);

CREATE SEQUENCE SEQ_TRAVEL_PLAN
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE SEQUENCE SEQ_PLAN_DAY
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE;

CREATE TABLE TRAVEL_PLAN (
    PLAN_ID               NUMBER(19)               NOT NULL,
    SOURCE_PLAN_ID        NUMBER(19),
    OWNER_MEMBER_ID       NUMBER(19)               NOT NULL,
    TITLE                 VARCHAR2(200)            NOT NULL,
    REGION_CODE           VARCHAR2(20)             NOT NULL,
    START_DATE            DATE                     NOT NULL,
    END_DATE              DATE                     NOT NULL,
    VISIBILITY            VARCHAR2(10)             DEFAULT 'PUBLIC' NOT NULL,
    PLAN_STATUS           VARCHAR2(10)             DEFAULT 'ACTIVE' NOT NULL,
    VERSION_NO            NUMBER(10)               DEFAULT 0 NOT NULL,
    DELETED_AT            TIMESTAMP WITH TIME ZONE,
    DELETED_BY_MEMBER_ID  NUMBER(19),
    RESTORED_AT           TIMESTAMP WITH TIME ZONE,
    RESTORED_BY_ADMIN_ID  NUMBER(19),
    CREATED_AT            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VIEW_COUNT            NUMBER(6)                DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TRAVEL_PLAN PRIMARY KEY (PLAN_ID),
    CONSTRAINT FK_PLAN_REGION
        FOREIGN KEY (REGION_CODE) REFERENCES REGION_MASTER (REGION_CODE),
    CONSTRAINT CK_PLAN_VISIBILITY
        CHECK (VISIBILITY IN ('PUBLIC', 'PRIVATE')),
    CONSTRAINT CK_PLAN_STATUS
        CHECK (PLAN_STATUS IN ('ACTIVE', 'DELETED')),
    CONSTRAINT CK_PLAN_DATE_RANGE
        CHECK (START_DATE <= END_DATE),
    CONSTRAINT CK_PLAN_DURATION
        CHECK (DATEDIFF('DAY', START_DATE, END_DATE) BETWEEN 0 AND 13),
    CONSTRAINT CK_PLAN_DELETE_STATE
        CHECK (
            (PLAN_STATUS = 'ACTIVE' AND DELETED_AT IS NULL AND DELETED_BY_MEMBER_ID IS NULL)
            OR (PLAN_STATUS = 'DELETED' AND DELETED_AT IS NOT NULL AND DELETED_BY_MEMBER_ID IS NOT NULL)
        ),
    CONSTRAINT CK_PLAN_VERSION
        CHECK (VERSION_NO >= 0),
    CONSTRAINT CK_PLAN_VIEW_COUNT
        CHECK (VIEW_COUNT >= 0)
);

CREATE TABLE PLAN_MEMBER (
    PLAN_ID          NUMBER(19)               NOT NULL,
    MEMBER_ID        NUMBER(19)               NOT NULL,
    PARTICIPANT_TYPE VARCHAR2(10)             NOT NULL,
    JOINED_AT        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_PLAN_MEMBER PRIMARY KEY (PLAN_ID, MEMBER_ID),
    CONSTRAINT FK_PLAN_MEMBER_PLAN
        FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID),
    CONSTRAINT CK_PLAN_PARTICIPANT_TYPE
        CHECK (PARTICIPANT_TYPE IN ('CREATOR', 'INVITEE'))
);

CREATE TABLE PLAN_DAY (
    PLAN_DAY_ID      NUMBER(19) NOT NULL,
    PLAN_ID          NUMBER(19) NOT NULL,
    DAY_NO           NUMBER(2)  NOT NULL,
    TRAVEL_DATE      DATE       NOT NULL,
    SCHEDULE_VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PLAN_DAY PRIMARY KEY (PLAN_DAY_ID),
    CONSTRAINT UK_PLAN_DAY_NO UNIQUE (PLAN_ID, DAY_NO),
    CONSTRAINT UK_PLAN_DAY_DATE UNIQUE (PLAN_ID, TRAVEL_DATE),
    CONSTRAINT FK_PLAN_DAY_PLAN
        FOREIGN KEY (PLAN_ID) REFERENCES TRAVEL_PLAN (PLAN_ID),
    CONSTRAINT CK_PLAN_DAY_NO
        CHECK (DAY_NO BETWEEN 1 AND 14),
    CONSTRAINT CK_PLAN_DAY_VERSION
        CHECK (SCHEDULE_VERSION >= 0)
);

CREATE INDEX IX_PLAN_OWNER_UPDATED
    ON TRAVEL_PLAN (OWNER_MEMBER_ID, UPDATED_AT DESC);

CREATE INDEX IX_PLAN_MEMBER_MEMBER
    ON PLAN_MEMBER (MEMBER_ID, PLAN_ID);
